apiVersion: v1
kind: BuildConfig
metadata:
  creationTimestamp: null
  labels:
    application: ssl
  name: ssl
spec:
  nodeSelector: null
  output:
    to:
      kind: ImageStreamTag
      name: ssl:latest
  postCommit: {}
  resources: {}
  runPolicy: Serial
  source:
    binary: {}
    type: Binary
  strategy:
    sourceStrategy:
      from:
        kind: ImageStreamTag
        name: openjdk18-openshift:latest
    type: Source
  triggers: []
status:
  lastVersion: 0
