apiVersion: v1
kind: DeploymentConfig
metadata:
  labels:
    application: ssl
  name: ssl
spec:
  replicas: 1
  selector:
    deploymentconfig: ssl
  strategy:
    activeDeadlineSeconds: 21600
    resources:
      requests:
        cpu: 500m
        memory: 512Mi
    rollingParams:
      intervalSeconds: 1
      maxSurge: 25%
      maxUnavailable: 25%
      timeoutSeconds: 600
      updatePeriodSeconds: 1
    type: Rolling
  template:
    metadata:
      labels:
        deploymentconfig: ssl
    spec:
      initContainers:
      - name: pem-to-keystore
        image: registry.access.redhat.com/redhat-sso-7/sso71-openshift:latest
        env:
          - name: keyfile
            value: /var/run/secrets/openshift.io/services_serving_certs/tls.key
          - name: crtfile
            value: /var/run/secrets/openshift.io/services_serving_certs/tls.crt
          - name: keystore_pkcs12
            value: /var/run/secrets/java.io/keystores/keystore.pkcs12
          - name: keystore_jks
            value: /var/run/secrets/java.io/keystores/keystore.jks
          - name: password
            value: changeit
        command: ['/bin/bash']
        args: ['-c', "openssl pkcs12 -export -inkey $keyfile -in $crtfile -out $keystore_pkcs12 -password pass:$password && keytool -importkeystore -noprompt -srckeystore $keystore_pkcs12 -srcstoretype pkcs12 -destkeystore $keystore_jks -storepass $password -srcstorepass $password -alias service"]
        volumeMounts:
          - name: keystore-volume2
            mountPath: /var/run/secrets/java.io/keystores
          - name: service-certs
            mountPath: /var/run/secrets/openshift.io/services_serving_certs
      containers:
      - image: docker-registry.default.svc:5000/mplat-reference-321/ssl@sha256:882021ee08fb715f2ba595ee57195e9d824580b43ca98a0139aff7a5c22b3933
        imagePullPolicy: Always
        name: ssl
        ports:
        - containerPort: 8443
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /var/run/secrets/java.io/keystores
          name: keystore-volume2
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - emptyDir: {}
        name: keystore-volume2
      - name: service-certs
        secret:
          defaultMode: 420
          secretName: service-certs
  test: false
  triggers:
  - type: ConfigChange
  - imageChangeParams:
      automatic: true
      containerNames:
      - ssl
      from:
        kind: ImageStreamTag
        name: ssl:latest
        namespace: mplat-reference-321
    type: ImageChange
status:
  availableReplicas: 0
  latestVersion: 0
  observedGeneration: 0
  replicas: 0
  unavailableReplicas: 0
  updatedReplicas: 0
