---
apiVersion: v1
kind: Service
metadata:
  name: java-pod
  annotations:
    service.alpha.openshift.io/serving-cert-secret-name: service-certs
  labels:
    app: java-pod
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: java-pod
---
apiVersion: v1
kind: DeploymentConfig
metadata:
  labels:
    app: java-pod
  name: java-pod
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: busybox-pod
    spec:
      containers:
      - name: java-pod
        image: registry.access.redhat.com/redhat-openjdk-18/openjdk18-openshift:latest
        command: ["sleep", "60000"]
        volumeMounts:
        - name: keystore-volume
          mountPath: /var/run/secrets/java.io/keystores
      initContainers:
      - name: pem-to-truststore
        image: registry.access.redhat.com/redhat-sso-7/sso71-openshift:latest
        env:
          - name: ca_bundle
            value: /var/run/secrets/kubernetes.io/serviceaccount/service-ca.crt
          - name: truststore_jks
            value: /var/run/secrets/java.io/keystores/truststore.jks
          - name: password
            value: changeit
        command: ['/bin/bash']
        args: ['-c', "keytool -importcert -noprompt -keystore $truststore_jks -file $ca_bundle -storepass $password -alias service"]
        volumeMounts:
          - name: keystore-volume
            mountPath: /var/run/secrets/java.io/keystores
      - name: pem-to-keystore
        image: registry.access.redhat.com/redhat-sso-7/sso71-openshift:latest
        env:
          - name: keyfile
            value: /var/run/secrets/openshift.io/services_serving_certs/tls.key
          - name: crtfile
            value: /var/run/secrets/openshift.io/services_serving_certs/tls.crt
          - name: keystore_pkcs12
            value: /var/run/secrets/java.io/keystores/keystore.pkcs12
          - name: keystore_jks
            value: /var/run/secrets/java.io/keystores/keystore.jks
          - name: password
            value: changeit
        command: ['/bin/bash']
        args: ['-c', "openssl pkcs12 -export -inkey $keyfile -in $crtfile -out $keystore_pkcs12 -password pass:$password && keytool -importkeystore -noprompt -srckeystore $keystore_pkcs12 -srcstoretype pkcs12 -destkeystore $keystore_jks -storepass $password -srcstorepass $password"]
        volumeMounts:
          - name: keystore-volume
            mountPath: /var/run/secrets/java.io/keystores
          - name: service-certs
            mountPath: /var/run/secrets/openshift.io/services_serving_certs
      volumes:
        - name: keystore-volume
          emtpyDir: {}
        - name: service-certs
          secret:
            secretName: service-certs 
