apiVersion: v1
kind: ImageStream
metadata:
  creationTimestamp: null
  generation: 1
  labels:
    application: ssl
  name: ssl
spec:
  lookupPolicy:
    local: false
  tags:
  - annotations: null
    from:
      kind: DockerImage
      name: docker-registry.default.svc:5000/mplat-reference-321/ssl:latest
    generation: 1
    importPolicy: {}
    name: latest
    referencePolicy:
      type: Source
status:
  dockerImageRepository: ""
